### ISSUE TITLE
Update Tool Information

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/phi-annotator-huggingface-bert#13]
### Problem description

The [tool controller](https://github.com/nlpsandbox/phi-annotator-huggingface-bert/blob/main/server/openapi_server/controllers/tool_controller.py) has not been changed since the default.

We need to reach out to David S. Lim (who fine-tuned the BERT model in question), and I think he should be considered a co-author of this tool. We also need to clarify licensing (base BERT is Apache 2.0, are all fine-tuned versions also Apache 2.0?)

**Comment by tschaffter** [comment]
Note: When implementing the multi-model approach used in the Spark repo, tool information can be parametrized, for example to name and describe the tool differently based on values from the configuration file.

https://github.com/nlpsandbox/phi-annotator-spark-nlp
