### ISSUE TITLE
Use DSLim's bert-large-ner

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/phi-annotator-huggingface-bert#14]
We should incorporate other NER models fine-tuned by DSLim (e.g. [bert-large-NER](https://huggingface.co/dslim/bert-large-NER)) into this tool.

### Describe the solution you'd like

We can publish multiple Docker containers from one GitHub repo. See Thomas's [example](https://github.com/nlpsandbox/phi-annotator-spark-nlp) (also see corresponding [Docker repo](https://www.synapse.org/#!Synapse:syn22277124/docker/)).

**Comment by tschaffter** [comment]
See the [Spark tool](https://github.com/nlpsandbox/phi-annotator-spark-nlp) for an example on how to implement a multi-model tool repo, i.e. 1 repository => n tools/docker images.

**Comment by tschaffter** [comment]
@cascadianblue Can you implement this second model so we can submit the two bert tools to the NLP Sandbox by Friday 10?

**Comment by tschaffter** [comment]
@cascadianblue Can we close this issue now that #24 has been merged?
