### ISSUE TITLE
Tool Controller is not Giving the Model Name + Info

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/phi-annotator-huggingface-bert#31]
### Problem description

Here is what I get for the output of `/tool`
```
{
  "apiVersion": "1.2.0",
  "author": "NLP Sandbox Team",
  "authorEmail": "team@nlpsandbox.io",
  "description": "Hugging Face PHI annotator ({config.model_name})",
  "license": "apache-2.0",
  "name": "phi-annotator-huggingface-",
  "repository": "github:nlpsandbox/phi-annotator-huggingface",
  "type": "nlpsandbox:phi-annotator",
  "url": "https://github.com/nlpsandbox/phi-annotator-huggingface",
  "version": "1.0.0"
}
```

#### Steps to reproduce the issue

1. Ran `docker run -p 80:8080 docker.synapse.org/syn22277123/phi-annotator-huggingface-bert-large-ner`
2. Went to `http://localhost/api/v1/ui/#/Tool/get_tool` in my browser

#### Expected behavior

- Should display the name of the huggingface model in the `/tool` controller

**Comment by cascadianblue** [comment]
On [this line](https://github.com/nlpsandbox/phi-annotator-huggingface-bert/blob/3228faf02103a8994cfc87bd3c06e5535e316def/server/openapi_server/config.py#L26), the `config_name` and `model_name` are drawn from environment variables. Are these variables accessible at runtime?

**Comment by tschaffter** [comment]
They should if the tool is started with docker-compose AND (the file `.env` exists OR the property [env_file](https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option) exists)... And now I see, you mean during evaluation?

This is why for the [Spark tool I pass the variable as build arguments](https://github.com/nlpsandbox/phi-annotator-spark-nlp/blob/main/.github/workflows/ci.yml#L157-L163). See also its Dockerfile that convert ARG to ENV.

**Comment by tschaffter** [comment]
Done in #32
